version: "3.8"

services:
  web:
    stdin_open: true # So that the serving is not exited with code 0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: "PRODUCTION"
    environment:
      TIMER_BACKGROUND: https://wallpaperplay.com/walls/full/0/7/6/29912.jpg
      TIMER_TARGET: "Wed Oct 28 2020 00:00:00 GMT+0100" # Get help with https://esqsoft.com/javascript_examples/date-to-epoch.htm
      TIMER_TITLE: "My birthday in"
    ports:
      - "3000:3000"