  
name: Client CI

on:
  push:
    paths:
      - ./**
      - .github/workflows/client.yml
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Run Buildx
        working-directory: ./client/
        run: |
          ls && docker buildx build \
            --platform linux/386,linux/amd64,linux/arm64 \
            --output "type=image" --push \
            --tag yooooomi/easy-countdown ./
